# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f1acbeafe524f1b806a13c85c54945d2ecd5a646a664034f5924db54f0ab232bc93929f2b7fe4d8e7c4e8af9b92ec49b61ed99954bfec7cc7081dbf652bc294

test:
  secret_key_base: 14a9d5582d1abcacb8e2188a4128f5619c667d3cb6b5b6a28756191267cf9b13d595e9cae600ce288426046b300fed7b3c0fd5609f32ba06bbe8155df9dded87

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
